@startuml
!theme plain
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName "Arial"
skinparam defaultFontSize 12
skinparam linetype ortho

skinparam rectangle {
  BackgroundColor white
  BorderColor black
  FontColor black
  FontSize 13
  FontStyle bold
}

skinparam usecase {
  BackgroundColor white
  BorderColor black
  FontColor black
  FontSize 13
  FontStyle bold
}

skinparam database {
  BackgroundColor white
  BorderColor black
  FontColor black
  FontSize 11
}

skinparam arrow {
  FontSize 11
  FontStyle bold
  Color #000000
}

title DFD Level 1

left to right direction

rectangle "User" as USER

usecase "1 Auth" as P1
usecase "2 Execute" as P2
usecase "3 Visualize" as P3
usecase "4 Dry Run" as P4
usecase "5 Complexity" as P5
usecase "6 History" as P6

rectangle "Judge0" as J0
database "D1 Accounts" as D1
database "D2 Snippets" as D2

USER <--> P1 : credentials
USER <--> P2 : code
USER <--> P3 : code
USER <--> P4 : code
USER <--> P5 : code
USER <--> P6 : commands

P2 <--> J0 : result
P3 <--> J0 : trace

P1 <--> D1 : user
P6 <--> D2 : snippets

@enduml